"use client";

import { useState } from "react";

interface CareerPathOption {
  role: string;
  currentFitPercent: number;
  keyStrengths: string[];
  missingSkills: string[];
  experienceNeeded?: string | null;
  transitionDifficulty: "EASY" | "MODERATE" | "CHALLENGING";
  recommendedPreparation: string[];
  rationale: string;
}

const DIFFICULTY_STYLES: Record<string, string> = {
  EASY: "bg-green-100 text-green-800",
  MODERATE: "bg-amber-100 text-amber-800",
  CHALLENGING: "bg-red-100 text-red-800",
};

export function CareerPathExplorer({
  initialPaths,
  initialCreatedAt,
  aiProviderIsMock,
}: {
  initialPaths: CareerPathOption[] | null;
  initialCreatedAt: string | null;
  aiProviderIsMock: boolean;
}) {
  const [paths, setPaths] = useState<CareerPathOption[] | null>(initialPaths);
  const [createdAt, setCreatedAt] = useState<string | null>(initialCreatedAt);
  const [isMock, setIsMock] = useState(aiProviderIsMock);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setStatus("loading");
    setError(null);
    try {
      const res = await fetch("/api/career-path", { method: "POST" });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Failed to generate career path prediction.");
        setStatus("error");
        return;
      }
      setPaths(data.paths);
      setCreatedAt(data.createdAt);
      setIsMock(Boolean(data.aiProvider?.includes("mock")));
      setStatus("idle");
    } catch {
      setError("Network error.");
      setStatus("error");
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between">
        <div>
          {createdAt && (
            <p className="text-xs text-slate-500">
              Last generated {new Date(createdAt).toLocaleString()}
            </p>
          )}
        </div>
        <button
          onClick={generate}
          disabled={status === "loading"}
          className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
        >
          {status === "loading" ? "Analyzing…" : paths ? "Regenerate" : "Predict my career path"}
        </button>
      </div>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {isMock && paths && (
        <div className="mt-3 rounded-md bg-amber-50 p-3 text-xs text-amber-800">
          This prediction was generated by a deterministic development placeholder
          (no ANTHROPIC_API_KEY configured), not a real AI model. It exists only to verify
          the pipeline end-to-end.
        </div>
      )}

      {paths && (
        <div className="mt-5 grid gap-4 sm:grid-cols-2">
          {paths.map((p, i) => (
            <div key={i} className="rounded-lg border border-slate-200 p-4">
              <div className="flex items-start justify-between gap-2">
                <h3 className="font-semibold text-slate-900">{p.role}</h3>
                <span
                  className={`flex-none rounded-full px-2 py-0.5 text-xs font-medium ${DIFFICULTY_STYLES[p.transitionDifficulty]}`}
                >
                  {p.transitionDifficulty.toLowerCase()}
                </span>
              </div>

              <div className="mt-2 flex items-center gap-2">
                <div className="h-2 w-full rounded-full bg-slate-100">
                  <div
                    className="h-2 rounded-full bg-blue-600"
                    style={{ width: `${p.currentFitPercent}%` }}
                  />
                </div>
                <span className="flex-none text-xs text-slate-500">{p.currentFitPercent}% fit now</span>
              </div>

              <p className="mt-3 text-sm text-slate-600">{p.rationale}</p>

              {p.keyStrengths.length > 0 && (
                <div className="mt-3">
                  <p className="text-xs font-semibold uppercase text-slate-500">Key strengths</p>
                  <ul className="mt-1 list-inside list-disc text-sm text-slate-700">
                    {p.keyStrengths.map((s, j) => (
                      <li key={j}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}

              {p.missingSkills.length > 0 && (
                <div className="mt-3">
                  <p className="text-xs font-semibold uppercase text-slate-500">Missing skills</p>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {p.missingSkills.map((s, j) => (
                      <span key={j} className="rounded-full bg-red-50 px-2 py-0.5 text-xs text-red-700">
                        {s}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {p.experienceNeeded && (
                <p className="mt-3 text-sm text-slate-600">
                  <span className="font-medium">Experience needed: </span>
                  {p.experienceNeeded}
                </p>
              )}

              {p.recommendedPreparation.length > 0 && (
                <div className="mt-3">
                  <p className="text-xs font-semibold uppercase text-slate-500">Recommended preparation</p>
                  <ul className="mt-1 list-inside list-disc text-sm text-slate-700">
                    {p.recommendedPreparation.map((s, j) => (
                      <li key={j}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
