"use client";

import { useState } from "react";

interface Match {
  requirementIndex: number;
  matchStatus: string;
  confidence: string;
  gapType: string;
  candidateEvidence: string | null;
  recommendedAction: string | null;
  priority: string | null;
  requirement: { rawText: string; category: string; importance: string } | null;
}

interface AnalysisResult {
  overallScore: number;
  categoryScores: Record<string, number | null>;
  recommendation: string;
  recommendationReason: string;
  strengths: string[];
  criticalGaps: string[];
  matches: Match[];
  aiProvider: string;
}

const STATUS_STYLES: Record<string, string> = {
  STRONG_MATCH: "bg-green-100 text-green-800",
  MATCH: "bg-green-100 text-green-800",
  PARTIAL_MATCH: "bg-amber-100 text-amber-800",
  EVIDENCE_UNCLEAR: "bg-amber-100 text-amber-800",
  GAP: "bg-red-100 text-red-800",
  OPTIONAL_GAP: "bg-slate-100 text-slate-700",
  CV_VISIBILITY_GAP: "bg-blue-100 text-blue-800",
};

export function JobFitAnalysis({ jobId }: { jobId: string }) {
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  async function runAnalysis() {
    setStatus("loading");
    setError(null);
    try {
      const res = await fetch(`/api/jobs/${jobId}/analyze`, { method: "POST" });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Analysis failed.");
        setStatus("error");
        return;
      }
      setResult(data);
      setStatus("idle");
    } catch {
      setError("Network error.");
      setStatus("error");
    }
  }

  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold text-slate-900">AI Job Fit Analysis</h2>
        <button
          onClick={runAnalysis}
          disabled={status === "loading"}
          className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
        >
          {status === "loading" ? "Analyzing…" : result ? "Re-run analysis" : "Analyze fit"}
        </button>
      </div>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {result && (
        <div className="mt-5 space-y-6">
          {result.aiProvider.includes("mock") && (
            <div className="rounded-md bg-amber-50 p-3 text-xs text-amber-800">
              This analysis was generated by a deterministic development placeholder
              (no ANTHROPIC_API_KEY configured), not a real AI model. It exists only to verify
              the pipeline end-to-end.
            </div>
          )}

          <div className="flex items-center gap-4">
            <div className="relative flex h-24 w-24 items-center justify-center rounded-full border-8 border-slate-100">
              <div
                className="absolute inset-0 rounded-full"
                style={{
                  background: `conic-gradient(#2563eb ${result.overallScore * 3.6}deg, #e2e8f0 0deg)`,
                  mask: "radial-gradient(farthest-side, transparent calc(100% - 8px), black calc(100% - 8px))",
                  WebkitMask:
                    "radial-gradient(farthest-side, transparent calc(100% - 8px), black calc(100% - 8px))",
                }}
              />
              <span className="text-xl font-bold text-slate-900">{result.overallScore}</span>
            </div>
            <div>
              <p className="font-semibold text-slate-900">{result.recommendation}</p>
              <p className="mt-1 text-sm text-slate-600">{result.recommendationReason}</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {Object.entries(result.categoryScores)
              .filter(([, v]) => v !== null)
              .map(([key, value]) => (
                <div key={key} className="rounded-md border border-slate-100 p-2 text-center">
                  <p className="text-xs capitalize text-slate-500">
                    {key.replace(/([A-Z])/g, " $1")}
                  </p>
                  <p className="font-semibold text-slate-900">{value}</p>
                </div>
              ))}
          </div>

          {result.strengths.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Strengths</h3>
              <ul className="mt-1 list-inside list-disc text-sm text-slate-700">
                {result.strengths.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </div>
          )}

          {result.criticalGaps.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Critical gaps</h3>
              <ul className="mt-1 list-inside list-disc text-sm text-red-700">
                {result.criticalGaps.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </div>
          )}

          <div>
            <h3 className="text-sm font-semibold text-slate-900">Requirement-by-requirement</h3>
            <div className="mt-2 overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="border-b border-slate-200 text-xs uppercase text-slate-500">
                    <th className="py-2 pr-3">Requirement</th>
                    <th className="py-2 pr-3">Importance</th>
                    <th className="py-2 pr-3">Status</th>
                    <th className="py-2 pr-3">Evidence</th>
                    <th className="py-2 pr-3">Recommended action</th>
                  </tr>
                </thead>
                <tbody>
                  {result.matches.map((m, i) => (
                    <tr key={i} className="border-b border-slate-100 align-top">
                      <td className="py-2 pr-3 font-medium text-slate-800">
                        {m.requirement?.rawText ?? "—"}
                      </td>
                      <td className="py-2 pr-3 text-slate-600">{m.requirement?.importance}</td>
                      <td className="py-2 pr-3">
                        <span
                          className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                            STATUS_STYLES[m.matchStatus] ?? "bg-slate-100 text-slate-700"
                          }`}
                        >
                          {m.matchStatus.replace(/_/g, " ")}
                        </span>
                      </td>
                      <td className="py-2 pr-3 text-slate-600">
                        {m.candidateEvidence ?? <span className="italic text-slate-400">Evidence not found in candidate profile.</span>}
                      </td>
                      <td className="py-2 pr-3 text-slate-600">{m.recommendedAction ?? "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
