"use client";

import { useState } from "react";

interface CourseSuggestion {
  courseTitle: string;
  provider: string;
  url: string | null;
  cost: string;
  certificateAvailable: boolean;
  estimatedDuration: string | null;
  level: string;
  skillsCovered: string[];
  gapCoveragePercent: number;
  reasonRecommended: string;
  providerCredibility: string;
}

interface Batch {
  id: string;
  skillName: string;
  recommendations: CourseSuggestion[];
  aiModel: string;
  verified: boolean;
  createdAt: string;
}

export function LearningEngine({
  recommendedSkills,
  initialBatches,
}: {
  recommendedSkills: Array<{ skillName: string; reason: string }>;
  initialBatches: Batch[];
}) {
  const [batches, setBatches] = useState<Batch[]>(initialBatches);
  const [loadingSkill, setLoadingSkill] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generateFor(skillName: string, context?: string) {
    setLoadingSkill(skillName);
    setError(null);
    try {
      const res = await fetch("/api/learning-recommendations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ skillName, context }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Failed to generate course recommendations.");
        return;
      }
      setBatches((prev) => [data.batch, ...prev.filter((b) => b.skillName !== skillName)]);
    } catch {
      setError("Network error.");
    } finally {
      setLoadingSkill(null);
    }
  }

  return (
    <div>
      <div className="rounded-md bg-amber-50 p-3 text-xs text-amber-800">
        Course suggestions are generated from general knowledge, not a live catalog check —
        course availability, pricing, and exact URLs are not verified in real time. Links go to a
        provider&apos;s search page rather than a specific course page, so you can confirm what&apos;s
        currently offered before enrolling.
      </div>

      {recommendedSkills.length > 0 && (
        <div className="mt-4 rounded-lg border border-slate-200 bg-white p-5">
          <h2 className="font-semibold text-slate-900">Recommended learning order</h2>
          <p className="mt-1 text-sm text-slate-500">
            From your Skill ROI analysis — highest priority gaps first.
          </p>
          <ul className="mt-3 space-y-2">
            {recommendedSkills.map((s) => (
              <li key={s.skillName} className="flex items-center justify-between rounded-md border border-slate-100 p-2">
                <div>
                  <p className="text-sm font-medium text-slate-800">{s.skillName}</p>
                  <p className="text-xs text-slate-500">{s.reason}</p>
                </div>
                <button
                  onClick={() => generateFor(s.skillName, s.reason)}
                  disabled={loadingSkill === s.skillName}
                  className="flex-none rounded-md bg-blue-600 px-2 py-1 text-xs font-medium text-white hover:bg-blue-700 disabled:opacity-50"
                >
                  {loadingSkill === s.skillName ? "Finding…" : "Find courses"}
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      <div className="mt-6 space-y-4">
        {batches.map((b) => (
          <div key={b.id} className="rounded-lg border border-slate-200 bg-white p-5">
            <h3 className="font-semibold text-slate-900">{b.skillName}</h3>
            {b.aiModel.includes("mock") && (
              <div className="mt-2 rounded-md bg-amber-50 p-2 text-xs text-amber-800">
                Generated by a deterministic development placeholder, not a real AI model.
              </div>
            )}
            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              {b.recommendations.map((c, i) => (
                <div key={i} className="rounded-md border border-slate-100 p-3">
                  <p className="text-sm font-medium text-slate-900">{c.courseTitle}</p>
                  <p className="text-xs text-slate-500">
                    {c.provider} · {c.level.toLowerCase()} · {c.cost}
                  </p>
                  {c.certificateAvailable && (
                    <span className="mt-1 inline-block rounded-full bg-green-50 px-2 py-0.5 text-xs text-green-700">
                      Certificate available
                    </span>
                  )}
                  <p className="mt-2 text-xs text-slate-600">{c.reasonRecommended}</p>
                  {c.url && (
                    <a
                      href={c.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mt-2 inline-block text-xs text-blue-600 hover:underline"
                    >
                      Search on {c.provider} →
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
