"use client";

import { useState } from "react";

interface LinkedinContent {
  headline: string;
  about: string;
  experienceDescriptions: Array<{ jobTitle: string; employer: string; description: string }>;
  skillsToAdd: string[];
  featuredContentSuggestions: string[];
  keywords: string[];
}

export function LinkedinOptimizer({
  initialContent,
  initialCreatedAt,
  aiModelIsMock,
}: {
  initialContent: LinkedinContent | null;
  initialCreatedAt: string | null;
  aiModelIsMock: boolean;
}) {
  const [content, setContent] = useState<LinkedinContent | null>(initialContent);
  const [createdAt, setCreatedAt] = useState<string | null>(initialCreatedAt);
  const [isMock, setIsMock] = useState(aiModelIsMock);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setStatus("loading");
    setError(null);
    try {
      const res = await fetch("/api/linkedin-optimizer", { method: "POST" });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Failed to generate suggestions.");
        setStatus("error");
        return;
      }
      setContent(data.content);
      setCreatedAt(data.createdAt);
      setIsMock(Boolean(data.aiProvider?.includes("mock")));
      setStatus("idle");
    } catch {
      setError("Network error.");
      setStatus("error");
    }
  }

  return (
    <div>
      <div className="rounded-md bg-blue-50 p-3 text-xs text-blue-800">
        These are suggested text you can copy into LinkedIn yourself — this tool does not connect
        to or update any LinkedIn account.
      </div>

      <div className="mt-4 flex items-center justify-between">
        {createdAt && (
          <p className="text-xs text-slate-500">Last generated {new Date(createdAt).toLocaleString()}</p>
        )}
        <button
          onClick={generate}
          disabled={status === "loading"}
          className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
        >
          {status === "loading" ? "Generating…" : content ? "Regenerate" : "Generate suggestions"}
        </button>
      </div>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {isMock && content && (
        <div className="mt-3 rounded-md bg-amber-50 p-3 text-xs text-amber-800">
          Generated by a deterministic development placeholder, not a real AI model —
          pipeline verification only.
        </div>
      )}

      {content && (
        <div className="mt-5 space-y-5">
          <section>
            <h3 className="text-xs font-semibold uppercase text-slate-500">Headline</h3>
            <p className="mt-1 rounded-md border border-slate-200 bg-white p-3 text-sm text-slate-800">
              {content.headline}
            </p>
          </section>

          <section>
            <h3 className="text-xs font-semibold uppercase text-slate-500">About</h3>
            <p className="mt-1 whitespace-pre-line rounded-md border border-slate-200 bg-white p-3 text-sm text-slate-700">
              {content.about}
            </p>
          </section>

          {content.experienceDescriptions.length > 0 && (
            <section>
              <h3 className="text-xs font-semibold uppercase text-slate-500">Experience descriptions</h3>
              <div className="mt-1 space-y-2">
                {content.experienceDescriptions.map((e, i) => (
                  <div key={i} className="rounded-md border border-slate-200 bg-white p-3">
                    <p className="text-sm font-medium text-slate-800">
                      {e.jobTitle} — {e.employer}
                    </p>
                    <p className="mt-1 text-sm text-slate-600">{e.description}</p>
                  </div>
                ))}
              </div>
            </section>
          )}

          <section>
            <h3 className="text-xs font-semibold uppercase text-slate-500">Skills to add</h3>
            <div className="mt-1 flex flex-wrap gap-1">
              {content.skillsToAdd.map((s, i) => (
                <span key={i} className="rounded-full bg-blue-50 px-2 py-0.5 text-xs text-blue-700">
                  {s}
                </span>
              ))}
            </div>
          </section>

          {content.featuredContentSuggestions.length > 0 && (
            <section>
              <h3 className="text-xs font-semibold uppercase text-slate-500">Featured section ideas</h3>
              <ul className="mt-1 list-inside list-disc text-sm text-slate-700">
                {content.featuredContentSuggestions.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </section>
          )}

          <section>
            <h3 className="text-xs font-semibold uppercase text-slate-500">Keywords</h3>
            <div className="mt-1 flex flex-wrap gap-1">
              {content.keywords.map((k, i) => (
                <span key={i} className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
                  {k}
                </span>
              ))}
            </div>
          </section>
        </div>
      )}
    </div>
  );
}
