"use client";

import { useState } from "react";

interface SimilarRole {
  title: string;
  relationshipType: string;
  suitabilityPercent: number;
  rationale: string;
}

const RELATIONSHIP_LABELS: Record<string, string> = {
  SIMILAR_TITLE: "Similar title",
  ALTERNATIVE_TITLE: "Alternative title",
  ADJACENT_ROLE: "Adjacent role",
  CAREER_PROGRESSION: "Career progression",
};

export function SimilarRoles({ jobId }: { jobId: string }) {
  const [suggestions, setSuggestions] = useState<SimilarRole[] | null>(null);
  const [isMock, setIsMock] = useState(false);
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setStatus("loading");
    setError(null);
    try {
      const res = await fetch(`/api/jobs/${jobId}/similar-roles`, { method: "POST" });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Failed to find similar roles.");
        setStatus("error");
        return;
      }
      setSuggestions(data.suggestions);
      setIsMock(Boolean(data.aiProvider?.includes("mock")));
      setStatus("idle");
    } catch {
      setError("Network error.");
      setStatus("error");
    }
  }

  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold text-slate-900">Similar & Adjacent Roles</h2>
        <button
          onClick={generate}
          disabled={status === "loading"}
          className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
        >
          {status === "loading" ? "Searching…" : suggestions ? "Refresh" : "Find similar roles"}
        </button>
      </div>

      {error && <p className="mt-2 text-sm text-red-600">{error}</p>}

      {isMock && suggestions && (
        <div className="mt-3 rounded-md bg-amber-50 p-3 text-xs text-amber-800">
          Generated by a deterministic development placeholder, not a real AI model —
          pipeline verification only.
        </div>
      )}

      {suggestions && (
        <div className="mt-3 space-y-2">
          {suggestions.map((s, i) => (
            <div key={i} className="rounded-md border border-slate-100 p-3">
              <div className="flex items-center justify-between">
                <p className="font-medium text-slate-900">{s.title}</p>
                <span className="text-xs text-slate-500">{s.suitabilityPercent}% suitability</span>
              </div>
              <span className="mt-1 inline-block rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
                {RELATIONSHIP_LABELS[s.relationshipType] ?? s.relationshipType}
              </span>
              <p className="mt-1 text-sm text-slate-600">{s.rationale}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
